on:
  push:
    branches:
      - main
name: 🚀 Deploy website
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Pegar o ultimo codigo
        uses: actions/checkout@v2

      - name: 📂 Sincronizar arquivos
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.ftp_host_escola }}
          username: ${{ secrets.ftp_user_escola }}
          password: ${{ secrets.ftp_password_escola }}
          server-dir: web/escola/